services:
  mcp-gateway:
    build:
      context: mcp_gateway
      dockerfile: Dockerfile_mcp_gateway
    platform: linux/amd64
    ports:
      - 8000:8000
    environment:
      MCP_GATEWAY_TOKEN_SECRET: 123321
      VNC_AUTH: false
      REDIS_URL: redis://:redisSrv@123@localhost:6379/0
    restart: on-failure:3
    deploy:
      resources:
        limits:
          memory: 2G

  container-server:
    build:
      context: .
      dockerfile: container_server/Dockerfile_container_server
    platform: linux/amd64
    restart: on-failure:3
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      VIRTUALPC_MCP_SERVER_IMAGE_ID: aworld-mcp-server
      GATEWAY_SERVER_ADDR: http://mcp-gateway:8000
    deploy:
      resources:
        limits:
          memory: 8G

  redis-server:
    image: redis:7.2-alpine
    platform: linux/amd64
    ports:
      - 6379:6379
    volumes:
      - ./.data/redis-data:/data
    environment:
      - REDIS_PASSWORD=redisSrv@123
    restart: on-failure:3
    deploy:
      resources:
        limits:
          memory: 2G